version: '3.8'

services:
  backend:
    build: ./backend
    container_name: tbb-backend
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    env_file:
      - .env
    volumes:
      - ./backend/logs:/app/logs
    restart: unless-stopped
    networks:
      - tbb-network
    environment:
      # These settings allow the frontend container to communicate with backend
      # while still restricting external access
      - ALLOWED_IPS=${ALLOWED_IPS:-*}
      - ALLOW_DOCKER_INTERNAL=true

  frontend:
    build: ./frontend
    container_name: tbb-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - tbb-network
    environment:
      - REACT_APP_API_BASE_URL=http://backend:8000

networks:
  tbb-network:
    driver: bridge 