version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: tbb-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - tbb-network
    environment:
      - REACT_APP_API_BASE_URL=${BACKEND_URL:-http://localhost:8000}

networks:
  tbb-network:
    driver: bridge 